
import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageUrl = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || 'https://picsum.photos/seed/placeholder/800/600';

export const products: Product[] = [
  {
    id: 'terry-bath-towel',
    name: 'Terry Bath Towel',
    description: 'Soft and highly absorbent terry towels, perfect for daily bath use. Made from 100% cotton, offering durability and comfort for hotel guests.',
    shortSpecs: '100% Cotton, Soft & Absorbent',
    category: {
      type: 'towel',
      material: 'Terry',
      usage: 'bath',
    },
    images: [getImageUrl('product-1-1'), getImageUrl('product-1-2')],
    moq: '100 units',
    leadTime: '4-6 Weeks',
    keyFeatures: 'Soft, highly absorbent, perfect for daily bath use',
  },
  {
    id: 'velour-bath-towel',
    name: 'Velour Bath Towel',
    description: 'Plush and luxurious velour towels with a smooth, sheared finish that provides a premium feel. Ideal for high-end hotels and suites.',
    shortSpecs: '100% Cotton, Plush & Luxurious',
    category: {
      type: 'towel',
      material: 'Velour',
      usage: 'bath',
    },
    images: [getImageUrl('product-3-1'), getImageUrl('product-2-2')],
    moq: '100 units',
    leadTime: '5-7 Weeks',
    keyFeatures: 'Plush, luxurious, smooth finish for a premium feel',
  },
  {
    id: 'waffle-weave-towel',
    name: 'Waffle Weave Towel',
    description: 'Lightweight and quick-drying waffle weave towels. The distinctive texture is not only stylish but also highly functional for spa and wellness areas.',
    shortSpecs: '100% Cotton, Lightweight & Quick-Drying',
    category: {
      type: 'towel',
      material: 'Waffle',
      usage: 'spa',
    },
    images: [getImageUrl('product-2-1'), getImageUrl('hero-2')],
    moq: '150 units',
    leadTime: '4-6 Weeks',
    keyFeatures: 'Lightweight, quick-drying, ideal for spa and wellness areas',
  },
  {
    id: 'jacquard-towel',
    name: 'Jacquard Towel',
    description: 'Elegant towels featuring intricate patterns woven directly into the fabric. Perfect for creating a sophisticated, branded look or for monogrammed designs in luxury establishments.',
    shortSpecs: '100% Cotton, Woven Pattern',
    category: {
      type: 'towel',
      material: 'Jacquard',
      usage: 'bath',
    },
    images: [getImageUrl('product-4-1'), getImageUrl('hero-3')],
    moq: '200 units',
    leadTime: '6-8 Weeks',
    keyFeatures: 'Elegant patterned towels, perfect for branded or monogrammed designs',
  },
  {
    id: 'microcotton-towel',
    name: 'Microcotton Towel',
    description: 'Experience ultra-soft, lightweight, and long-lasting luxury with Microcotton towels. Made from high-quality long-staple cotton for superior absorbency and a silky feel.',
    shortSpecs: '100% Microcotton, Ultra-Soft & Lightweight',
    category: {
      type: 'towel',
      material: 'Microcotton',
      usage: 'bath',
    },
    images: [getImageUrl('product-1-1'), getImageUrl('product-1-2')],
    moq: '150 units',
    leadTime: '5-7 Weeks',
    keyFeatures: 'Ultra-soft, lightweight, long-lasting luxury',
  },
  {
    id: 'terry-hand-towel',
    name: 'Terry Hand Towel',
    description: 'Durable and absorbent terry hand towels designed for high-traffic guest bathrooms. A perfect blend of practicality and comfort.',
    shortSpecs: '100% Cotton, Durable & Absorbent',
    category: {
      type: 'towel',
      material: 'Terry',
      usage: 'hand-face',
    },
    images: [getImageUrl('product-1-2')],
    moq: '250 units',
    leadTime: '3-5 Weeks',
    keyFeatures: 'Durable and absorbent, suitable for guest bathrooms',
  },
  {
    id: 'waffle-bathrobe',
    name: 'Waffle Bathrobe',
    description: 'Quick-drying and comfortable waffle bathrobes, ideal for spa, gym, and pool areas. The lightweight design offers guests comfort without the bulk.',
    shortSpecs: '100% Cotton, Quick-Drying & Comfortable',
    category: {
      type: 'robe',
      material: 'Waffle',
      usage: 'spa',
    },
    images: [getImageUrl('product-2-1')],
    moq: '50 units',
    leadTime: '5-7 Weeks',
    keyFeatures: 'Quick-drying, comfortable, ideal for spa, gym, and pool',
  },
  {
    id: 'pool-towel',
    name: 'Pool Towel',
    description: 'Extra-long and fast-drying towels designed for poolside comfort. Engineered to be highly absorbent and resistant to chlorine and sun exposure.',
    shortSpecs: '100% Cotton, Extra-Long & Fast-Drying',
    category: {
      type: 'towel',
      material: 'Terry',
      usage: 'specialty',
    },
    images: [getImageUrl('product-1-1')],
    moq: '100 units',
    leadTime: '4-6 Weeks',
    keyFeatures: 'Extra-long, fast-drying towels for poolside use',
  },
   {
    id: 'customization-options',
    name: 'Full Customization Available',
    description: 'We offer extensive customization options to meet your exact specifications. Tailor the size, weight (GSM), patterns, branding, and color to perfectly match your brand identity and guest experience standards.',
    shortSpecs: 'Size, GSM, Weave, Branding, Color',
    category: {
      type: 'material',
      material: 'Custom',
      usage: 'commercial',
    },
    images: [getImageUrl('hero-1')],
    moq: 'Varies',
    leadTime: 'Varies',
    keyFeatures: 'Size, GSM, Patterns, Weave, Printing, Branding, Color, Finishing',
  },
];
