
import { Timestamp } from 'firebase/firestore';

export type Category = {
  id: string;
  name: string;
  slug: string;
  parentId: string | null;
  description?: string;
  imageUrl?: string;
};

export type Product = {
  id: string;
  name: string;
  slug: string;
  categoryId: string;
  description: string;
  images: string[];
  specifications: {
    size?: string;
    material?: string;
    gsm?: string;
    tc?: string;
    color?: string;
    features?: string;
    firmness?: string;
    height?: string;
    top?: string;
    fabric?: string;
    construction?: string;
    fasteners?: string;
    finishing?: string;
    colorFastness?: string;
    packaging?: string;
    absorbency?: string;
    shrinkage?: string;
    bathrobes?: string;
    slippers?: string;
    blackout?: string;
    frStandards?: string;
    stitching?: string;
    formulation?: string;
    compliance?: string;
    fragrance?: string;
    labeling?: string;
    soaps?: string;
    finish?: string;
    hardware?: string;
    durability?: string;
    frame?: string;
    foam?: string;
    upholstery?: string;
    mattresses?: string;
    porcelain?: string;
    cutlery?: string;
    glassware?: string;
    chafingDishes?: string;
    gnPans?: string;
    certifications?: string;
    trolleys?: string;
    cleaningTools?: string;
    chemicals?: string;
    design?: string;
    standards?: string;
    sterility?: string;
    biocompatibility?: string;
    shelfLife?: string;
    regulatory?: string;
    electricalSafety?: string;
    calibration?: string;
    userManual?: string;
    warranty?: string;
    hardness?: string;
    loadCapacity?: string;
    mechanism?: string;
    mattressPlatform?: string;
    casters?: string;
    chemicalComposition?: string;
    testing?: string;
    handling?: string;
    reusableTextiles?: string;
    disposableTextiles?: string;
    infectionControl?: string;
    plasticware?: string;
    kitContents?: string;
    durableCases?: string;
  };
  customizationOptions?: string[];
  moq: string;
  shortSpecs?: string;
  safetyInfo?: string;
  specSheetUrl?: string;
  published?: boolean;
};

export type Inquiry = {
  id: string;
  name: string;
  email: string;
  company?: string;
  phone?: string;
  message: string;
  products?: { id: string, qty: number }[];
  status: 'Enquired' | 'Under Discussion' | 'Order Confirmed' | 'Shipped' | 'Completed';
  createdAt: Timestamp;
};
